<label>Vendor: </label>
<?php $vendor_ = $block->getVendor( $block->getVendorId());?>
<div>
<?php echo $vendor_->getName();?>
</div>


<br/>
<label>Related Products: </label>
<?php $products = $block->getAssociatedProductcIds($block->getVendorId());?>
<?php foreach($products as $product_):?>
<div>
	<?php $url = $product_->getUrlModel()->getUrl($product_); ?>
	<a href="<?php echo $url;?>"><?php echo $product_->getSku();?></a>
</div>
<br/>
<?php endforeach;?>